version: '2'
services:
        databaseData:
               image: mongo:3.3
               entrypoint: /bin/bash
               volumes:
                       - $HOME/.lair/mongodb/data/db:/data/db
        database:
               image: mongo:3.3
               volumes_from:
                      - databaseData
               command: mongod --dbpath=/data/db --bind_ip=database --quiet --nounixsocket --replSet rs0
        lair:
                build:
                        context: ./app/
                        dockerfile: Dockerfile
                links:
                       - database
                depends_on:
                       - database
                       - lairapi
        lairapi:
                build:
                        context: ./api/
                        dockerfile: Dockerfile
                links:
                       - database
                depends_on:
                       -  database
        caddy:
                build:
                        context: ./proxy/
                        dockerfile: Dockerfile
                links:
                        - lair
                        - lairapi
                        - database
                ports:
                        - 11013:11013
                depends_on:
                        - lair
                        - lairapi
                        - database
