version: '2'
services:
        postgres:
                build:
                        context: ./db/
                        dockerfile: Dockerfile
        cli:
                build:
                        context: ./app/
                        dockerfile: Dockerfile
                depends_on:
                        - postgres
                links:
                        - postgres
                tty: true
                ports:
                        - "80:80"
                        - "443:443"
                        - "8080:8080"
                        - "8443:8443"
